"""Stays context — reservations, iCal feeds, stay task bundles, guest welcome.

See docs/specs/04-properties-and-stays.md.
"""

from app.domain.stays.guest_link_service import (
    AccessRecord,
    ChecklistItem,
    GuestAsset,
    GuestLinkGone,
    GuestLinkGoneReason,
    GuestLinkNotFound,
    GuestLinkRead,
    ResolvedGuestLink,
    ResolveResult,
    SettingsResolver,
    WelcomeBundle,
    WelcomeMergeInput,
    WelcomeResolver,
    mint_link,
    record_access,
    resolve_link,
    revoke_link,
)
from app.domain.stays.turnover_generator import (
    DEFAULT_AFTER_CHECKOUT_RULE_ID,
    DEFAULT_RULES,
    DEFAULT_TURNOVER_DURATION,
    GuestKind,
    HandleResult,
    ReservationContextResolver,
    RuleOutcome,
    SessionContextProvider,
    StaticReservationContextResolver,
    TurnoverRule,
    default_resolver,
    handle_reservation_upserted,
    register_subscriptions,
)

__all__ = [
    "DEFAULT_AFTER_CHECKOUT_RULE_ID",
    "DEFAULT_RULES",
    "DEFAULT_TURNOVER_DURATION",
    "AccessRecord",
    "ChecklistItem",
    "GuestAsset",
    "GuestKind",
    "GuestLinkGone",
    "GuestLinkGoneReason",
    "GuestLinkNotFound",
    "GuestLinkRead",
    "HandleResult",
    "ReservationContextResolver",
    "ResolveResult",
    "ResolvedGuestLink",
    "RuleOutcome",
    "SessionContextProvider",
    "SettingsResolver",
    "StaticReservationContextResolver",
    "TurnoverRule",
    "WelcomeBundle",
    "WelcomeMergeInput",
    "WelcomeResolver",
    "default_resolver",
    "handle_reservation_upserted",
    "mint_link",
    "record_access",
    "register_subscriptions",
    "resolve_link",
    "revoke_link",
]
