"""In-process typed event bus. See docs/specs/01 §"Boundary rules" #3."""

from app.events.bus import EventBus, bus
from app.events.registry import (
    Event,
    EventAlreadyRegistered,
    EventNotFound,
    get_event_type,
    register,
    registered_events,
)
from app.events.types import (
    ChatMessageSent,
    ExpenseApproved,
    ExpenseReimbursed,
    ExpenseRejected,
    ExpenseSubmitted,
    InventoryItemChanged,
    LlmAssignmentChanged,
    NotificationCreated,
    PayPeriodLocked,
    PayPeriodPaid,
    ShiftChanged,
    ShiftChangedAction,
    ShiftEnded,
    StayUpcoming,
    TaskCommentAdded,
    TaskCompleted,
    TaskCreated,
    TaskEvidenceAdded,
    TaskOverdue,
    TaskUpdated,
)

__all__ = [
    "ChatMessageSent",
    "Event",
    "EventAlreadyRegistered",
    "EventBus",
    "EventNotFound",
    "ExpenseApproved",
    "ExpenseReimbursed",
    "ExpenseRejected",
    "ExpenseSubmitted",
    "InventoryItemChanged",
    "LlmAssignmentChanged",
    "NotificationCreated",
    "PayPeriodLocked",
    "PayPeriodPaid",
    "ShiftChanged",
    "ShiftChangedAction",
    "ShiftEnded",
    "StayUpcoming",
    "TaskCommentAdded",
    "TaskCompleted",
    "TaskCreated",
    "TaskEvidenceAdded",
    "TaskOverdue",
    "TaskUpdated",
    "bus",
    "get_event_type",
    "register",
    "registered_events",
]
